remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
name: Deep Blue AI Lab
title: Deep Blue AI Lab
description: Deep Blue AI Lab, a subsidiary of ROM Robotics, established in 25 dec 2022.
