remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Welcome to Deep Blue AI Lab, a subsidiary of ROM Robotics 
description: Deep Blue AI Lab, established in early 2023, is a cutting-edge research facility specializing in artificial intelligence and machine learning. As a proud sub-company of ROM Robotics, our lab is dedicated to pushing the boundaries of AI technology and its applications. Our team of passionate researchers and engineers is committed to innovation, with a focus on developing intelligent solutions that contribute to the advancement of robotics. Explore the forefront of AI research with Deep Blue AI Lab, where we harness the power of technology to shape the future.
show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]
